run() is good until line 223,
mv_third_to_target_local is the first of a series of functions that need
    exception handling mixed in. The rest of the dispatch functions like
    this need to be turned into a series of function calls in try/except,
    but don't just pass, raise exceptions and log properly.
rename_branch in shell is just about there, given the update to the
    process_logger function (now process_runner), and can take hints from
    set_current_branch.

Keep in mind when you're making the decision to touch an error handling
    point whether you want the stack trace logged and/or printed, whether
    you want a custom message logged and/or printed, and whether you want
    the program to crash.
